name: CI Pipeline with otel tracing

# Define when the workflow runs
# making some changes to trigger workflow
on:
  workflow_run:
    workflows: ['*']
    types: [completed]
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions: read-all

env:
  ACTION_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OTEL_EXPORTER_OTLP_ENDPOINT: https://xnj93051.live.dynatrace.com/api/v2/otlp/
  OTLP_PROTOCOL: HTTP
  WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
  WORKFLOW_RUN_NAME: ${{ github.event.workflow_run.name }}
  OTEL_EXPORTER_OTLP_HEADERS: Authorization=Api-Token ${{ secrets.DYNATRACE_OTEL_API_TOKEN }}
  GITHUB_DEBUG: true
  
jobs:
  OTLP-GitHubAction-Exporter :
    name: OTLP GitHubAction Exporter
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
      
#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '18'
        
 #     - name: Install dependencies
 #       run: npm install
      
 #     - name: Run tests
 #       run: npm test
      
      - name: Run OTLP GitHubAction Exporter
        uses: StephenGoodall/OTLP-GitHubAction-Exporter@v3
